# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RYWAppnFLuTMq4HCHyPnVAInDKudlb14
"""

import pandas as pd
from collections import defaultdict

#from google.colab import files
#uploaded = files.upload()

data = pd.read_excel('playball.xlsx')
print(data)

list(data.columns)
print("Enter The Unknown Sample\n")

unknown = dict()
for col in range(len(list(data.columns))-1):
  print(data.columns[col],":",end="")
  unknown[data.columns[col]]=input()
  print()
print("The Entered Unknown Sample Is:",str(unknown))

print("The classes of",data.columns[-1],"are :",data["Play ball"].unique())

classes = dict(data["Play ball"].value_counts())
prob = dict()
print("Their Respective Counts Are:\n",classes)
print("Their Respective Probabilities Are:")
for i in classes.copy():
  prob[i] = classes[i]/data.shape[0]
print(prob)

countdict = defaultdict(dict)
probdict = defaultdict(dict)
print("The Count and Corresponding Probabilities are:\n")
for i in classes.copy():
  for j in unknown.copy():
    count = 0
    for k in range(data.shape[0]):
      if data.at[k,j] == unknown[j] and data.at[k,data.columns[-1]]==i:
        count+=1
    countdict[i][unknown[j]]=count
    probdict[i][unknown[j]]=count/classes[i]
print(str(countdict))
print(str(probdict))

print("The Posteriori Probabilities are:\n")
postprob = defaultdict(dict)
for i in probdict.copy():
  mul = 1
  for j in probdict[i].copy():
    mul = probdict[i][j]*mul
  postprob[i]=mul*prob[i]
for i in postprob.copy():
  print("P(",i,"/X)=",postprob[i])

maxpost = -9999
for i in postprob.copy():
  if maxpost <= postprob[i]:
    maxpost = postprob[i]
for i in postprob.copy():
  if maxpost == postprob[i]:
    print("The Following Unknown Sample Is Classified As:",i)

